[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
  
# Явно указываем стабильный образ сборки
[context.production.environment]
  NPM_INSTALL_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200